### ISSUE TITLE
Count noop writes as writes in stats

### ISSUE THREAD

**Issue by danielmewes** [rethinkdb/rethinkdb#3777]
If you do something like
```
r.table('t').insert({id: "a"})
r.table('t').insert({id: "a"})
```

The first write will show up in the queries per second graph as a write (as it should), but the second one doesn't show up, neither as a write or a read.

This is because the second write doesn't actually change any data.
However it still performs a read into the btree and causes server load, so I think we should still count it.

**Comment by Tryneus** [comment]
I don't think a no-op write should count as a write, but it should count as a read - nothing is getting committed to the btree, but we do look at the row in the cache (and load it off disk, if necessary).  There seems to be a problem right now that `point_write_t` and `point_delete_t` operations are not counting the read in stats.  The read is still counted in range replaces.  Investigating.

**Comment by mlucy** [comment]
IMO I think it's weird to issue a write query and see no writes happening.  I don't think anybody would complain if we counted protocol writes that didn't result in btree writes as writes in the stats.

**Comment by Tryneus** [comment]
This is why we have an `unchanged` field in the write result.  I think it is inconsistent to tell the user who ran the query that we didn't do a write, but then tell anyone watching the stats that we did.

**Comment by Tryneus** [comment]
In addition, the stats we show should be a good indication at a glance of how much load the cluster is under.  If we are reporting writes that didn't happen in the stats, users will think their cluster is under much more load than it actually is, and they cannot get a good sense of the capabilities of their machines.

**Comment by danielmewes** [comment]
Writes that don't change anything aren't quite like reads either though with respect to load, since they still acquire exclusive locks in the btree.

**Comment by mlucy** [comment]
IMO the `writes` and `reads` we report in the stats should correspond as closely as possible tot he number of `write` and `read` queries users issue.  Users probably have a pretty good mental model of that, whereas writing `r.table('test').update({a: 1})` and seeing your reads spike while your writes stay at 0 is just confusing.

I think it's OK for some of the operations we report as writes to be cheaper than other operations we report as writes (the same is true for soft durability and hard durability writes, which are lumped together).

**Comment by Tryneus** [comment]
I can change it to that behavior without too much trouble, I take it we will also count reads and writes that error on a non-existant row as a reads and writes in the stats?

I'm taking this opportunity to add tests for this, which is something we've needed for a while, but is now not ridiculously complicated due to the `rethinkdb.stats` table.

**Comment by mlucy** [comment]
Here's what my (probably totally irrational) internal model would expect:
* Writes that error don't show up (including writes that error on a non-existent row).
* Writes that succeed but don't actually need to change the btree show up as one write.
* Writes that succeed show up as one write (obviously).
* Writes that succeed on rows with secondary indexes show up as one write.
* Reads that error before retrieving a value don't show up.
* Reads that error after retrieving a value (e.g. in the `map`) show up as one read.
* Reads that succeed show up as one read.

If that matches what other people would expect, I think we should do it; if it doesn't I think we should probably just pick a reasonable rule and stick with it.  (I think the reason I would expect noop writes but not error writes to show up is because in my mind "I'm performing writes but no writes show up on the graph" means "something is wrong".)

**Comment by danielmewes** [comment]
On a similarly irrational basis, I agree with @mlucy's model. It sounds like what I would expect.�

**Comment by Tryneus** [comment]
How do you think a delete should look if the row exists, e.g. `r.table('foo').get(100).delete()`?  One read and one write, or just one write?  The query contains a get, which I think means you expect it to register as a read.  However, the value is never read out of the btree, so maybe it shouldn't show as a read.

**Comment by danielmewes** [comment]
I don't think we should make this a bigger change than necessary.

The scenario where this came up was just running `rethinkdb import -f ...` where all the documents already existed in the table. It caused a lot of server load and slowed other reads down significantly, but didn't show up in the QPS graph.

I think this is all we should change. Either counting such queries as writes or as reads would be better than what we have now. Either seems ok, though I think always counting write queries as writes even if they actually degrade to only a read is more intuitive.

About `table.get.delete`: While I can't say that doing otherwise would be strictly "wrong", I think `table.get.delete`, `table.get.update` and `table.get.replace` should count only as a write and not as a read as well. If nothing else, it makes it easier to plot the graph because you don't have to worry about the read and write lines being exactly the same with one hiding the other.

**Comment by Tryneus** [comment]
@danielmewes, we have some other glaring bugs in how many keys read/written we are reporting.  Here's what I've found from testing:

* replaces that don't change the row aren't reporting writes (the purpose of this issue)
* `table.get.update` and `table.get.replace` are counting a write for each index on the table
* secondary index post-construction is counting 1 read and 2 writes for each row (should be 1 read, 1 write)
* `table.get` for a row that doesn't exist still reports a read (this isn't as obviously wrong as the others)

**Comment by Tryneus** [comment]
Also, backfill is kind of confusing.  I had a table of 100 rows in one shard, and then resharded it across two servers, one of which was already hosting the primary.  I then see:
* server 1
  * 48 reads
  * 48 writes
* server 2
  * 0 reads
  * 48 writes

This is reasonable, server 1 transferred 48 rows to server 2, then removed them.  The behavior is much harder to understand when the table has three pre-existing secondary indexes:
* server 1
  * 48 reads
  * 144 writes
* server 2
  * 48 reads
  * 288 writes

**Comment by mlucy** [comment]
I would personally expect `table.get.delete` to show up as one write.  (I'm not sure what I would expect for `table.get.replace(f, non_atomic: true)`, but one read and one write in that case sounds slightly better because it will emphasize the performance characteristics of non-atomic writes for people.)

**Comment by mlucy** [comment]
Also also, in my opinion reads that try to retrieve a non-existent row should show up as reads -- we still "read" something, it was just `nil`.  I would expect e.g. reads on a table with no master available not to show up as reads though (that was what I meant by "error before retrieving a value").

**Comment by Tryneus** [comment]
I put the test script up in review 2614 and tagged @mlucy and @danielmewes as reviewers.  It contains a significant range of read/write queries.  Please discuss the expected stats for each query there so we can have well-defined expected behavior for the server.

**Comment by Tryneus** [comment]
The script in `test/interface/precise_stats.py` now codifies what we expect certain queries to result in.  The test is currently failing, and we should fix the server's stats reporting before 2.0.

**Comment by danielmewes** [comment]
Since we have a little more time before the final 2.0 release, this might be worth still getting in there.

**Comment by Tryneus** [comment]
Working on this now.

**Comment by Tryneus** [comment]
Fix is up in review 2763.

**Comment by Tryneus** [comment]
The fix has been approved and merged to `next` in commit 11a9481, and cherry-picked into `v2.0.x` in commit 0f28653.  Will be in release 2.0.
