### ISSUE TITLE
rdb_erase_small_range() should erase deletion entries too

### ISSUE THREAD

**Issue by timmaxw** [rethinkdb/rethinkdb#4039]
The `rdb_erase_small_range()` function iterates over a range using `btree_depth_first_traversal()`, finds all key-value pairs, and dispatches deletion operations to erase those key-value pairs. However, it ignores deletion entries, so they will be left in the B-tree even after the erasing is done. I don't think this causes any bugs, but it wastes disk space.

**Comment by danielmewes** [comment]
Isn't the space used for deletion entries in the leaf nodes fixed?

**Comment by timmaxw** [comment]
I'm not really sure. You're probably right that this wastes O(1) disk space. I still think we should fix it because it's a counterintuitive behavior and it might lead to bugs.

**Comment by danielmewes** [comment]
...to answer my own question: I guess it's just bounded, but not fixed so fewer deletion entries could free up a little bit of space for other entries. I'm not sure if this actually has any effects, since once we start needing that space for new entries, we would probably expire those deletions (but maybe not in all cases? Not sure).

@timmaxw that makes sense. I could see it leading to bugs, so we should fix it.
